import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import SideBar from "@/app/components/SideBar";
import { ThemeContextProvider } from "@/app/context/ThemeToggle";
const inter = Inter({ subsets: ["latin"]})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen  bg-[var(--background)] text-[var(--foreground)] `}>
        <ThemeContextProvider>
        <div className="flex min-h-screen  "> 
          <SideBar />  
           <main className=" flex-1 p-6 bg-[var(--background)] text-[var(--foreground)]  ">
             {children}
          </main>
        </div>
        </ThemeContextProvider>
       </body>
    </html>
  );
}
